### ISSUE TITLE
Create ERD for Cats Social

### ISSUE THREAD

**Issue by malikilamalik** [sedelinggam/cats-social#1]
Buat ERD menggunakan [dbdiagram](https://dbdiagram.io/)

Requirement
-Authentication & Authorization
--User
---id (UUID)
---email (VARCHAR)
---password(VARCHAR 72)
---name(VARCHAR 50)
---created_at (timestamptz)
--User Token
---id (UUID)
---user_id (UUID) -> foreign key id
---token (VARCHAR)
---expired_at(timestamptz)
-Manage Cats
-Match Cats

**Comment by shevaathalla** [comment]
-- Cat
--- id(UUID)
--- user_id (UUID) -> owner id
--- name (VARCHAR 100)
--- race (ENUM("Persian"|"Maine Coon"|"Siamese"|"Ragdoll"|"Bengal"|"Sphynx"|"British Shorthair"|"Abyssinian"|"Scottish Fold"|"Birman"))
--- sex (ENUM("male"|"female"))
--- age_in_month(SMALL INT)
--- image_urls(JSON)
--- description(TEXT)
--- is_already_matched(TINY INT)
--- partner_id (UUID) -> self reference

**Comment by abdmmar** [comment]
Nyoba bikin ERD based on https://openidea-projectsprint.notion.site/Cats-Social-9e7639a6a68748c38c67f81d9ab3c769 di https://dbdiagram.io/d, CMIIW.

![image](https://github.com/sedelinggam/cats-social/assets/50788123/efc833a8-77b3-4c88-9045-9a814932a5e0)

```
Table user {
  id uuid
  name varchar(50)
  password varchar(72)
  email varchar
  createdAt timestamp
}

Table cat {
  id uuid
  userId uuid
  name varchar(30)
  race enum("Persian","Maine Coon","Siamese","Ragdoll","Bengal","Sphynx","British Shorthair","Abyssinian","Scottish Fold","Birman")
  sex enum("male","female")
  ageInMonth smallint
  imageUrls text[]
  description varchar(200)
  isAlreadyMatched enum(true,false)
  matchId uuid
}

Table match {
  id uuid
  matchCatId id
  userCatId id
  createdAt timestamp
  message varchar(120)
}

Ref: cat.userId > user.id // each user can have many cats
Ref: match.userCatId > cat.userId // each cat can have many matches
```

Question:
- Apakah ketika user nge-reject match (`POST /v1/cat/match/reject`), cat match data di table `match` bakal didelete/soft-delete juga? soalnya ngga ada requirement-nya.
- Apakah perlu ada column `status` buat `approved/rejected`?

Basically this meme 🤣:
![image](https://github.com/sedelinggam/cats-social/assets/50788123/602b6a56-452e-4fd3-9623-7df5d8598108)

**Comment by achmadmuzaki14** [comment]
kak jadi pake table user_tokens ga ya berarti

**Comment by shevaathalla** [comment]
1. mungkin soft deletenya ada di catnya soalnya kucing yg sudah match lalu dihapus data kucingnya masi tetep bisa lihat
2. oiya perlu table match karena yg antri bisa lebih dari 1 dan perlu status juga, tp statusnya menurutku gaperlu reject karena kalo rejected itu langsung remove, jadi mungkin bisa "pending" & "approved" aja
3. enum utk boolean type ntar jadinya string

**Comment by achmadmuzaki14** [comment]
bang tu berarti gajadi pake table user_tokens ya

**Comment by achmadmuzaki14** [comment]
tadi aku juga coba bikin bang https://dbdocs.io/achmadmuzaki14/cats_social?view=relationships

pas: cats123

> bang tu berarti gajadi pake table user_tokens ya

**Comment by abdmmar** [comment]
@achmadmuzaki14 ah iya, kayaknya perlu ditambahin table `user_tokens`, daripada setup redis lagi :)

@shevaathalla 
1. maksudnya soft-delete di cat-nya itu gimana ya? data cat di table `cat`-nya dihapus kah? kalo di table match masih bisa diliat, berarti ngga bisa dihapus karena di table match kan perlu ngereference ke data cat di table `cat`?
2. ah iya butuh "pending" status. nah ini mau soft-delete atau hard-delete? kalo soft-delete kyknya masih perlu status "rejected". masih bingung juga sih ini siapa yg bisa ngelakuin approval wkwkkw
3. TIL, better pake tinyint (0/1) berarti ya? atau boolean?

**Comment by malikilamalik** [comment]
@shevaathalla nggak data kucingnya harusnya kedelete pas diget tapi di matchnya masih ada data kucingnya.
@abdmmar gak boleh pake redis pak.
1. soft delete itu ditambahin deleted_at mar, jadi kalau delete nggak didelete kolomnya tapi update deleted_atnya jadi hari ini. pas get atau get list tambah where deleted_at is null
3. pake boolean aja pak, postgresql kayaknya support boolean https://www.postgresql.org/docs/current/datatype-boolean.html

**Comment by malikilamalik** [comment]
Gak perlu matchID di cat, kalau dari match ke cat bisa pake userCatID atau matchCatID.
Ganti dari camel case ke snakecase, karena postgresql case sensitive "userId" == "userID".
Ganti timestamp ke timestamptz, tambah timezone biar gak pusing ketika get timezone +7
```
Table user {
  id uuid
  name varchar(50)
  password varchar(72)
  email varchar
  created_at timestampz
}

Table cat {
  id uuid
  user_id uuid
  name varchar(30)
  race enum("Persian","Maine Coon","Siamese","Ragdoll","Bengal","Sphynx","British Shorthair","Abyssinian","Scottish Fold","Birman")
  sex enum("male","female")
  age_in_month smallint
  image_urls text[]
  description varchar(200)
  is_already_matched boolean
  created_at timestampz
  deleted_at timestampz
  update_at timestampz
}

Table match {
  id uuid
  match_cat_id id
  user_cat_id id
  created_at timestampz
  message varchar(120)
}

Ref: cat.user_id > user.id // each user can have many cats
Ref: match.user_cat_id > cat.user_id // each cat can have many matches
```
