### ISSUE TITLE
[ Manage Cats ] Get List Cat

### ISSUE THREAD

**Issue by malikilamalik** [sedelinggam/cats-social#6]
- GET /v1/cat
    - Request
        - Param (all optional)
            - `id` limit the output based on the cat’s id
                - value should be a string
            - `limit` & `offset` limit the output of the data
                - default `limit=5&offset=0`
                - value should be a number
            - `race` filter based on race
                - enum of `"Persian"`|`"Maine Coon"`|`"Siamese"`|`"Ragdoll"`|`"Bengal"`|`"Sphynx"`|`"British Shorthair"`|`"Abyssinian"`|`"Scottish Fold"`|`"Birman"`
            - `sex` filter based on sex
                - enum of `"male"` | `"female"`
            - `isAlreadyMatched` filter based on match
                - enum of `true`|`false`
            - `ageInMonth` filter based on age
                - value should be a string, but parsed like this:
                    - `ageInMonth=>4` searches data that have more than 4 months
                    - `ageInMonth=<4` searches data that have less than 4 months
                    - `ageInMonth=4` searches data that have exact 4 month
            - `owned` filter based on the cat that the user own
                - value should be `true`/`false`
            - `search` display information that contains the name of search
                - value should be a string
    - Response
        - `200` successfully get cats
            
            ```jsx
            {
            	"message": "success",
            	"data": [ // ordered by newest first
            		{
            			"id": "", // use whatever id
            			"name": "", 
            			"race": "", 
            			"sex": "", 
            			"ageInMonth": 1, 
            			"imageUrls":[ 
            				"","",""
            			],
            			"description":"" // not null, minLength 1, maxLength 200
            			"isAlreadyMatched": true, // true if the cat is already matched
            			"createdAt": "" // should in ISO 8601 format
            		}
            	]
            }
            ```
            
        - `401` request token is missing or expired

**Comment by abdmmar** [comment]
Closed by #14
